### PR TITLE
kiran

### PR DESCRIPTION
**Pull request by kiran96969**

### CODE REVIEW

**Comment by kiran96969** [comment]
new file

**Comment by kiran96969** [comment]
add new file

**Comment by kiran96969** [comment]
html page

**Comment by kiran96969** [comment]
css

**Comment by kiran96969** [comment]
new file

**Comment by LearnWithPrasanth** [comment]
Create a folder like ThopsTechID-Name. The create assignments and practice subfolders in your ThopsTechID-Name folder. Move your files into their corresponding folders.

Fix the conflicts and raise the PR again.

**Pull request closed without merging**
